"""empty message

Revision ID: 556f3d6129c5
Revises: 962d96bb91da
Create Date: 2022-11-02 14:45:36.859723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556f3d6129c5'
down_revision = '962d96bb91da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_complete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
