"""empty message

Revision ID: 962d96bb91da
Revises: d617034d0caa
Create Date: 2022-11-02 14:34:24.344769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962d96bb91da'
down_revision = 'd617034d0caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_complete')
    # ### end Alembic commands ###
